### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by rcherbonnier** [neurospin/zeijemol#3]
File "zeijemol/views/gallery.py", line 21, in <module>
    import cubes.snapview as zeijemol
ImportError: No module named snapview
instance not started: No module named snapview

+

UnboundLocalError: UnboundLocalError: local variable 'index' referenced before assignment
File zeijemol/views/status.py, line 133, function call:
  records=records, csv_export=True, index=index,

+

UnboundLocalError: UnboundLocalError: local variable 'wave_name' referenced before assignment
File zeijemol/views/status.py, line 136, function call:
  title="Ratings".format(wave_name))

**Comment by AGrigis** [comment]
I fix this naming issue.
